---
sudo: required
notifications:
    email: true
addons:
    apt_packages:
        - parallel
services:
    - docker
branches:
    only:
        - master
        - develop
        - feature
before_install:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - sudo pip install docker-compose
    - IMAGES=$(find . -type f -name docker-compose.yaml ! -path "./.tests/*" -printf '%h\n' | sort)
install:
    - |
        # General configuration
        stty cols 120
        # tfold is a helper to create folded reports
        tfold () {
            title=$1
            fold=$(echo $title | sed -r 's/[^-_A-Za-z\d]+/./g')
            shift
            echo -e "travis_fold:start:$fold\\n\\e[1;34m$title\\e[0m"
            bash -xc "$*" 2>&1 &&
                echo -e "\\e[32mOK\\e[0m $title\\n\\ntravis_fold:end:$fold" ||
                ( echo -e "\\e[41mKO\\e[0m $title\\n" && exit 1 )
        }
        export -f tfold
    - |
        run_builds () {
            set -e
            echo "$IMAGES" | parallel --gnu -j10% "tfold {} 'cd {} && docker-compose build > log || (tail -n 1000 log && false)'"
        }
    - |
        run_tests () {
            set -e
            echo "$IMAGES" | parallel --gnu -j10% "tfold 'test {}' 'cd ./.tests/{} && make test; make clean'"
        }
script:
    - docker --version
    - docker-compose --version
    - (run_builds)
    - (run_tests)
