test:
	docker-compose run --rm qatools php --version
	docker-compose run --rm qatools pdepend --version
	docker-compose run --rm qatools phan --version
	docker-compose run --rm qatools php-cs-fixer --version
	docker-compose run --rm qatools phpcbf --version
	docker-compose run --rm qatools phpcf --version
	docker-compose run --rm qatools phpcpd --version
	docker-compose run --rm qatools phpcs --version
	docker-compose run --rm qatools phpdcd --version
	docker-compose run --rm qatools phploc --version
	docker-compose run --rm qatools phpmd --version
	docker-compose run --rm qatools phpmetrics --version
	docker-compose run --rm qatools phpstan --version
	docker-compose run --rm qatools security-checker --version

clean:
