version: '3'

services:
    mkdocs:
        image: guillaumedelre/mkdocs
        ports:
            - "9080:9080"
        environment:
            - MKDOCS_VERSION=1.0.4
        volumes:
            - ${PWD}:/project
